Remove Qpid
theforeman/puppet-katello pull request #491
Opened 2024-02-21 18:55 UTC by ehelms

2024-02-21 19:37 UTC, chris1984 approved these changes

2024-03-20 08:15 UTC, evgeni requested changes
readme and fixtures.yml still refer to qpid ;-)

2024-03-20 16:22 UTC, ekohl approved these changes

2024-03-20 16:22 UTC, ekohl commented on README.md
> +This module is designed to setup a Katello server, and including Candlepin.
```suggestion
This module is designed to setup a Katello server, including Candlepin.
```

2024-03-21 00:16 UTC, evgeni approved these changes

2024-03-21 00:52 UTC, merged